module.exports.Dictionary = {
  titles: {
    objective: ["objective", "objectives"],
    summary: ["summary"],
    hobby: ["hobby", "hobbies"],
    technology: ["technology", "technologies"],
    experience: ["experience", "work experience"],
    education: ["education"],
    skills: [
      "skills",
      "Skills & Expertise",
      "technology",
      "technologies",
      "SKILLS & ABILITIES",
    ],
    languages: ["languages"],
    projects: ["projects", "project"],
    links: ["links"],
    contacts: ["contacts"],
    positions: ["positions", "position"],
    profiles: [
      "profile",
      "profiles",
      "social connect",
      "social-profiles",
      "social profiles",
    ],
    awards: ["awards"],
    honors: ["honors"],
    additional: ["additional"],
    certification: ["certification", "certifications"],
    interests: ["interests"],
  },
};
